// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uelyqikobhjrosibqzxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlbHlxaWtvYmhqcm9zaWJxenhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzYxNjUsImV4cCI6MjA1OTI1MjE2NX0.ZwQPbNmzEx5ps2oEQq8RRtOowwF3RxIOtUnlP2VWHNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);